/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContactUi {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLContactUiElement extends Components.ContactUi, HTMLStencilElement {
    }
    var HTMLContactUiElement: {
        prototype: HTMLContactUiElement;
        new (): HTMLContactUiElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "contact-ui": HTMLContactUiElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ContactUi {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "contact-ui": ContactUi;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "contact-ui": LocalJSX.ContactUi & JSXBase.HTMLAttributes<HTMLContactUiElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
